#pragma once
void RunNetAddrTests();
void RunUdpSocketTests();
void RunSourceQueryTests();
void RunClientIdTests();
void RunClockTests();
void RunRandomTests();
void RunMemoryFootprintTests();
void RunLogFileTests();
void RunFfiTextTests();
void RunLocalInputGateTests();
void RunHostCallbackTests();
void RunHostProbeTests();
void RunLanScannerTests();
void RunAppDataFileTests();
