#pragma once
void RunWireTests();
void RunReassemblerTests();
void RunFecTests();
void RunRetransmitCacheTests();
void RunSessionTests();
void RunInputTests();
void RunControlTests();
void RunStreamSizeTests();
void RunClockOffsetTests();
void RunQualityLadderTests();
void RunDiagTests();
void RunMediaContractTests();
void RunBeaconTests();
