
set(DESKHUB_OPUS_ROOT ${CMAKE_CURRENT_LIST_DIR}/../third_party/opus)

function(deskhub_opus_target out_var)
    if(WIN32)
        set(${out_var} x86_64-pc-windows-msvc PARENT_SCOPE)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
        if(ANDROID_ABI STREQUAL "arm64-v8a")
            set(${out_var} aarch64-linux-android PARENT_SCOPE)
        elseif(ANDROID_ABI STREQUAL "armeabi-v7a")
            set(${out_var} armv7-linux-androideabi PARENT_SCOPE)
        else()
            set(${out_var} x86_64-linux-android PARENT_SCOPE)
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        if(CMAKE_OSX_SYSROOT MATCHES "Simulator")
            set(${out_var} aarch64-apple-ios-sim PARENT_SCOPE)
        else()
            set(${out_var} aarch64-apple-ios PARENT_SCOPE)
        endif()
    elseif(APPLE)
        if(EXISTS ${DESKHUB_OPUS_ROOT}/macos-universal/libopus.a)
            set(${out_var} macos-universal PARENT_SCOPE)
        elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
            set(${out_var} x86_64-apple-darwin PARENT_SCOPE)
        else()
            set(${out_var} aarch64-apple-darwin PARENT_SCOPE)
        endif()
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
        set(${out_var} aarch64-unknown-linux-gnu PARENT_SCOPE)
    else()
        set(${out_var} x86_64-unknown-linux-gnu PARENT_SCOPE)
    endif()
endfunction()

deskhub_opus_target(DESKHUB_OPUS_TARGET)

if(MSVC)
    set(DESKHUB_OPUS_ARTIFACT opus.lib)
else()
    set(DESKHUB_OPUS_ARTIFACT libopus.a)
endif()

set(DESKHUB_OPUS_LIB ${DESKHUB_OPUS_ROOT}/${DESKHUB_OPUS_TARGET}/${DESKHUB_OPUS_ARTIFACT})
set(DESKHUB_OPUS_INCLUDE ${DESKHUB_OPUS_ROOT}/include)

if(EXISTS ${DESKHUB_OPUS_LIB} AND EXISTS ${DESKHUB_OPUS_INCLUDE}/opus/opus.h)
    set(DESKHUB_OPUS_FOUND ON)
else()
    set(DESKHUB_OPUS_FOUND OFF)
endif()

if(DESKHUB_OPUS_FOUND AND NOT TARGET deskhub::opus)
    add_library(deskhub::opus STATIC IMPORTED GLOBAL)
    set_target_properties(deskhub::opus PROPERTIES
        IMPORTED_LOCATION ${DESKHUB_OPUS_LIB}
        INTERFACE_INCLUDE_DIRECTORIES ${DESKHUB_OPUS_INCLUDE})

    if(NOT WIN32)
        set_property(TARGET deskhub::opus APPEND PROPERTY INTERFACE_LINK_LIBRARIES m)
    endif()
endif()
